helpdesk_user:
    resource: "@helpdeskUserBundle/Resources/config/routing.yml"
    prefix:   /

helpdesk_soporte:
    resource: "@helpdeskSoporteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


