security: 
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext       
            
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
 
    providers:
        in_memory:
            memory:
                users:
                    mario:  { password: 123456, roles: [ 'ROLE_USER' ] }
                    admin: { password: 123456, roles: [ 'ROLE_ADMIN' ] }            
 
    firewalls:
        main:
            pattern: /.*
            provider: in_memory
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: MiClaveSegura
                lifetime: 1800
                path: /.*
                domain: ~
            security: true
            anonymous: true
            
    access_control:
        - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /user, roles: ROLE_USER }
        - { path: /admin, roles: ROLE_ADMIN }
        - { path: /.*, roles: ROLE_USER }        
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
   