# Submenu Solicitudes #    
login:
    pattern:   /login
    defaults:  { _controller: helpdeskSoporteBundle:Security:login }
    
login_check:
    pattern:   /login_check

logout:
    path:   /logout
    
helpdesk_inicio_soporte:
    path:     /
    defaults: { _controller: helpdeskSoporteBundle:Inicio:inicio }    

helpdesk_solicitudes_listar:
    path:     /solicitudes/listar
    defaults: { _controller: helpdeskSoporteBundle:Solicitudes:listar }
    
helpdesk_solicitudes_nuevo:
    path:     /solicitudes/nuevo
    defaults: { _controller: helpdeskSoporteBundle:Solicitudes:nuevo }
    
helpdesk_solicitudes_editar:
    path:     /solicitudes/editar/{codigoSolicitudPk}
    defaults: { _controller: helpdeskSoporteBundle:Solicitudes:editar }
    
helpdesk_solicitudes_eliminar:
    path:     /solicitudes/eliminar/{codigoSolicitudPk}
    defaults: { _controller: helpdeskSoporteBundle:Solicitudes:eliminar }
    
helpdesk_solicitudes_solucion:
    path:     /solicitudes/solucion/{codigoSolicitudPk}
    defaults: { _controller: helpdeskSoporteBundle:Solicitudes:solucion }    
    
# Submenu Usuarios#
helpdesk_usuarios_listar:
    path:     /usuarios/listar
    defaults: { _controller: helpdeskSoporteBundle:Usuarios:listar }
    
helpdesk_usuarios_nuevo:
    path:     /usuarios/nuevo
    defaults: { _controller: helpdeskSoporteBundle:Usuarios:nuevo }   
    
helpdesk_usuarios_editar:
    path:     /usuarios/editar{codigoUsuarioPk}
    defaults: { _controller: helpdeskSoporteBundle:Usuarios:editar }    

# Submenu Tipo Solicitud#
helpdesk_solicitudestipos_listar:
    path:     /solicitudestipos/listar
    defaults: { _controller: helpdeskSoporteBundle:SolicitudesTipos:listar }
    
helpdesk_solicitudestipos_nuevo:
    path:     /solicitudestipos/nuevo
    defaults: { _controller: helpdeskSoporteBundle:SolicitudesTipos:nuevo }   
    
helpdesk_solicitudestipos_editar:
    path:     /solicitudestipos/editar{codigoTipoSolicitudPk}
    defaults: { _controller: helpdeskSoporteBundle:SolicitudesTipos:editar } 
    
    